apiVersion: v1
kind: Pod
metadata:
  name: signed-image-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox:1.34.1@sha256:415fbd89e5344c96acf449d94a6f956dbed62e18e835fc83e064db33a34bd549
      command: ["sh", "-c", 'echo "Hello, world!"']