apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: tls-svc-csr
spec:
  request: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQmV6Q0NBU0lDQVFBd1VERVZN
    Qk1HQTFVRUNoTU1jM2x6ZEdWdE9tNXZaR1Z6TVRjd05RWURWUVFERXk1egplWE4wWlcwNmJtOWta
    VHAwYkhNdGNHOWtMblJzY3kxMFpYTjBMbkJ2WkM1amJIVnpkR1Z5TG14dlkyRnNNRmt3CkV3WUhL
    b1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFaTljSzIxZ0VMLzdmUnpuSXRKbGJkYTl6S2IvVjM0
    UmsKbVVIa01MbVlVZERycUp4bUhOclRMaExGQXlWYTc5N2xsWmRNRnZHbTZYTE82UVpkYXhLdjRh
    QndNRzRHQ1NxRwpTSWIzRFFFSkRqRmhNRjh3WFFZRFZSMFJCRll3VklJaWRHeHpMWE4yWXk1MGJI
    TXRkR1Z6ZEM1emRtTXVZMngxCmMzUmxjaTVzYjJOaGJJSWlkR3h6TFhCdlpDNTBiSE10ZEdWemRD
    NXdiMlF1WTJ4MWMzUmxjaTVzYjJOaGJJY0UKd0FBQ0dJY0VDZ0FpQWpBS0JnZ3Foa2pPUFFRREFn
    TkhBREJFQWlCV2NVRWVVQWpEK0ZHSHQwWU5HUDNyNE85TQpqcG1tLytIVGdPTHVhaGdRWEFJZ1p1
    RjRreFJMbWVWQnFMOW8yN3pOSmV2c0dkT1dreUQ3ZnpIV1EzUTJxbUU9Ci0tLS0tRU5EIENFUlRJ
    RklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kubelet-serving
  usages:
  - digital signature
  - key encipherment
  - server auth