apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-analysis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-analysis-deployment
  template:
    metadata:
      labels:
        app: static-analysis-deployment
    spec:
      hostIPC: false
      hostNetwork: false
      hostPID: false
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          securityContext:
            privileged: false