apiVersion: v1
kind: Pod
metadata:
  name: immutability-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.21.0
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
        readOnlyRootFilesystem: false
