apiVersion: v1
kind: Pod
metadata:
  name: apparmor-disk-write
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        [
          "sh",
          "-c",
          'while true; do echo "I write to the disk!" > diskwrite.log; sleep 5; done',
        ]
