apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-viewer-sa
  namespace: sa-permissions-test
automountServiceAccountToken: true
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-viewer-role
  namespace: sa-permissions-test
rules:
  - apiGroups: [""]
    resources: ["pod"]
    verbs: ["get", "list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-viewer-rb
  namespace: sa-permissions-test
subjects:
  - kind: ServiceAccount
    name: pod-viewer-sa
    namespace: auth
roleRef:
  kind: Role
  name: pod-viewer-role
  apiGroup: rbac.authorization.k8s.io
