apiVersion: v1
kind: Pod
metadata:
  name: falco-test-pod
spec:
  containers:
    - name: falco-test
      image: busybox:1.35
      command: ["sh", "-c", "while true; do cat /etc/shadow; sleep 5; done"]
