apiVersion: v1
kind: Pod
metadata:
  name: gcr-busybox
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: gcr.io/google-containers/busybox
      command: ["sh", "-c", "sleep 3600"]
